image: ubuntu:20.04

variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - build_deps
  - build

before_script:
  - apt-get update && apt-get install -y
      build-essential
      ccache
      cmake
      git
  - ./BuildLinux.sh -u

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ccache/
    - deps/build/destdir/

build_deps:
  stage: build_deps
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - chmod +x BuildLinux.sh
    - ./BuildLinux.sh -cd
  artifacts:
    paths:
      - deps/build/destdir/

linux-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - chmod +x BuildLinux.sh
    - ./BuildLinux.sh -csi
  artifacts:
    paths:
      - build/CrealityPrint*.AppImage
    expire_in: 1 week
