image: ${UBUNTU_IMAGE}

variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - build_deps
  - build

before_script:
  - apt-get update && apt-get install -y
      build-essential
      ccache
      cmake
      git
  - ./BuildLinux.sh -u

cache:
  key: ${CI_COMMIT_REF_SLUG}-${UBUNTU_IMAGE}
  paths:
    - ccache/
    - deps/build/destdir/

build_deps_20_04:
  stage: build_deps
  image: ubuntu:20.04
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - chmod +x BuildLinux.sh
    - ./BuildLinux.sh -cd
  artifacts:
    paths:
      - deps/build/destdir/
    expire_in: 1 week

build_20_04:
  stage: build
  image: ubuntu:20.04
  needs:
    - build_deps_20_04
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - chmod +x BuildLinux.sh
    - ./BuildLinux.sh -csi
  artifacts:
    paths:
      - build/CrealityPrint*.AppImage
    expire_in: 1 week

build_deps_24_04:
  stage: build_deps
  image: ubuntu:24.04
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - chmod +x BuildLinux.sh
    - ./BuildLinux.sh -cd
  artifacts:
    paths:
      - deps/build/destdir/
    expire_in: 1 week

build_24_04:
  stage: build
  image: ubuntu:24.04
  needs:
    - build_deps_24_04
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - chmod +x BuildLinux.sh
    - ./BuildLinux.sh -csi
  artifacts:
    paths:
      - build/CrealityPrint*.AppImage
    expire_in: 1 week
